apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-show-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: thanhnguyen0708/last-show-backend:amd64-v1
          ports:
            - containerPort: 8000
              hostPort: 8000 # Map directly to EC2 IP to save Load Balancer $$$
